version: "3.8"

services:
  config-service:
    image: sihemhsin/config-service:latest
    container_name: config-service
    ports:
      - "5555:5555"
    networks:
      - microservices-net

  eureka-service:
    image: sihemhsin/eureka-service:latest
    container_name: eureka-service
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservices-net

  gateway-service:
    image: sihemhsin/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - eureka-service
    networks:
      - microservices-net

  client-service:
    image: sihemhsin/client-service:latest
    container_name: client-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-service
    networks:
      - microservices-net

  produit-service:
    image: sihemhsin/produit-service:latest
    container_name: produit-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service
    networks:
      - microservices-net

  facture-service:
    image: sihemhsin/facture-service:latest
    container_name: facture-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-service
    networks:
      - microservices-net

networks:
  microservices-net:
